export const ADD = "ADD";
export const SUBTRACT = "SUBTRACT";

export const GET_ARTICLE_LIST = "GET_ARTICLE_LIST";
export const GET_ARTICLE_DETAIL = "GET_ARTICLE_DETAIL";
export const UPDATE_ARTICLE_DETAIL = "UPDATE_ARTICLE_DETAIL";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
